---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: redis
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:5.0.5
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        ports:
        - containerPort: 6379
